version: "3.6"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/default.conf.template:/etc/nginx/templates/default.conf.template"
      - ./cms:/var/www/html/cms
      - ./app:/var/www/html/app
      - ./nginx/certs:/etc/certs
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: .template
      CMS_DOMAIN: ${CMS_DOMAIN}
      APP_DOMAIN: ${APP_DOMAIN}
    depends_on:
      - php
      - nextjs
    restart: always

  mysql:
    image: mariadb:lts
    container_name: ${APP_NAME}-mysql
    command: --lower_case_table_names=2
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: always
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: ${APP_NAME}-php
    volumes:
      - ./cms:/var/www/html/cms
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WP_ENV: ${WP_ENV}
      WP_HOME: ${WP_HOME}
      WP_SITEURL: ${WP_SITEURL}
      AUTH_KEY: ${AUTH_KEY}
      SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${LOGGED_IN_KEY}
      NONCE_KEY: ${NONCE_KEY}
      AUTH_SALT: ${AUTH_SALT}
      SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${LOGGED_IN_SALT}
      NONCE_SALT: ${NONCE_SALT}

  mailhog:
    container_name: ${APP_NAME}-mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  composer:
    image: composer
    container_name: ${APP_NAME}-composer
    working_dir: /var/www/html/cms
    restart: "no"
    command: composer install --ignore-platform-reqs
    volumes:
      - ./cms:/var/www/html/cms

  nextjs:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        NPM_RC: ${NPM_RC}
    container_name: ${APP_NAME}-nextjs
    # volumes:
    #   - ./app:/app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - php
      - nginx
      - mysql
