version: "3.6"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/:/etc/nginx/templates/"
      - ./bedrock:/var/www/html
      - ./certs:/etc/certs
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template"
      - "DOMAIN=${DOMAIN}"
    depends_on:
      - php
    restart: always

  mysql:
    image: mariadb:lts
    container_name: ${APP_NAME}-mysql
    command: --lower_case_table_names=2
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    restart: always
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: ${APP_NAME}-php
    volumes:
      - ./bedrock:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    volumes:
      - ./php/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "8082:80"
    links:
      - mysql:mysql

  mailhog:
    container_name: ${APP_NAME}-mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  composer:
    image: composer
    container_name: ${APP_NAME}-composer
    working_dir: /var/www/html
    restart: "no"
    command: composer install --ignore-platform-reqs
    volumes:
      - ./bedrock:/var/www/html

  nextjs:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-nextjs
    # volumes:
    #   - ./app:/app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - php
      - nginx
      - mysql
